---
# tasks file for webserver
- name: Install Webserver
  ansible.builtin.apt:
    name: "{{ webserver_package }}"
    state: present

- name: Start and Enable Webserver
  ansible.builtin.service:
    name: "{{ webserver_package }}"
    state: started
    enabled: yes
