---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
- name: nginx-instance
  image: ubuntu:20.04
  pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra

scenario:
  name: default
