---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
- name: nginx-test-instance
  image: ubuntu:latest
  pre_build_image: true
  privileged: true
  command: "/lib/systemd/systemd"
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro


provisioner:
  name: ansible

verifier:
  name: testinfra

scenario:
  name: default
