---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
- name: nginx-test-instance
  image: ubuntu:latest
  pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra

scenario:
  name: default
