---
- name: Prepare Host | Bootstrap core dependencies
  hosts: all
  gather_facts: no
  # This play should be run with a user that has root privileges without sudo,
  # e.g., by connecting as the 'root' user itself.
  # Example command: ansible-playbook prepare.yml -u root

  tasks:
    - name: Bootstrap sudo and python3
      raw: |
        if command -v sudo >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
          echo "Sudo and Python3 already installed."
        else
          apt-get -y update && apt-get install -y sudo python3-minimal python3-apt
        fi
      changed_when: false
      failed_when: false

    - name: Gather facts after installing python
      # Now that python is installed, we can gather facts
      setup:

    - name: Install common dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - wget
          - unattended-upgrades
        state: present
        update_cache: yes # You can update cache here again safely
