---
- name: Prepare container for testing
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for testing
      apt:
        name:
          - curl
          - sudo
          - procps
        state: present
