---
- name: Prepare
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install common dependencies for Ansible
    apt:
      name:
      - python3
      - python3-apt
      - sudo
      - ca-certificates
      - curl
      - wget
      state: present

  - name: Ensure the "unattended-upgrades" package is installed
    apt:
      name: unattended-upgrades
      state: present
