---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy Docker containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ molecule_yml.platforms }}"
