- name: Create User
  user:
    name: ansible
    shell: /bin/bash
    groups: sudo
    create_home: yes
    state: present

- name: Create Directory .ssh
  file:
    path: /home/ansible/.ssh
    state: directory
    mode: '0700'
    owner: ansible
    group: ansible

- name: Copy SSH Key
  copy:
    src: authorized_keys
    dest: /home/ansible/.ssh/authorized_keys
    mode: '0600'
    owner: ansible
    group: ansible
    
