---
# tasks file for dbserver
- name: Install Database Server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Start and Enable MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Set Root Password
  ansible.builtin.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host_all: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
