---
- name: Install Basic Tools
  package:
    name: "{{common_packages}}"
    state: present
    update_cache: yes

- name: Install Webservers
  package: 
    name: "{{ansible_os_family == 'Debian' | ternary(debian_service, redhat_service)}}"
    state: present

- name: Check Web Server Status
  command: systemctl is-active "{{ ansible_os_family == 'Debian' | ternary(debian_service, redhat_service) }}"
  register: webserver_status
  changed_when: false

- name: Restart Web Server if Not Active
  when: webserver_status.stdout != "active"
  notify: Restart Web Server




  