---
# tasks file for roles/firewall
- name: Install community.general.ufw
  ansible.builtin.apt:
    name: community.general.ufw
    state: present
    update_cache: yes

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

