---
# tasks file for firewall
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow Ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ firewall_allowed_ports }}"

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
    policy: deny
