---
- name: Install Python 3.9 using deadsnakes PPA
  hosts: all
  become: true

  tasks:
    - name: Ensure deadsnakes PPA is added
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3.9 and related packages
      apt:
        name:
          - python3.9
          - python3.9-venv
          - python3.9-dev
        state: present

