---
- name: Prepare Ubuntu instances for Ansible role testing
  hosts: all
  gather_facts: no

  tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: Install common dependencies for Ansible
    ansible.builtin.apt:
      name:
      - python3
      - python3-apt
      - sudo
      - ca-certificates
      - curl
      - wget
      state: present
    when: ansible_os_family == 'Debian'

  - name: Ensure the "unattended-upgrades" package is installed (good practice)
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present
    when: ansible_os_family == 'Debian'

  - name: Ensure python is in the PATH for Ansible
    ansible.builtin.raw: "ln -s /usr/bin/python3 /usr/bin/python"
    args:
      creates: /usr/bin/python
    changed_when: false
    when: ansible_os_family == 'Debian' and not ansible_python_interpreter.startswith('/usr/bin/python')
