- name: Create User
  user:
    name: rullabcd
    shell: /bin/bash
    groups: sudo
    create_home: yes
    state: present

- name: Create .ssh Dir
  file:
    path: /home/rullabcd/.ssh
    state: directory
    mode: '0700'
    owner: rullabcd
    group: rullabcd

- name: Copy SSH Key
  copy:
    src: authorized_keys
    dest: /home/rullabcd/.ssh/authorized_keys
    mode: '0600'
    owner: rullabcd
    group: rullabcd
    
