---
# tasks file for nginx
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  become: yes

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: yes
