---
- name: Install Packages Loop
  hosts: all
  become: yes
  vars:
    packages:
    - curl
    - git
    - unzip

  tasks:
  - name: Install Packages
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop: "{{packages}}"
