---
- name: Setup User
  hosts: all
  become: true
  vars:
  - user: "rullabcd"

  tasks:
  - name: Create User
    ansible.builtin.user:
      name: "{{ user }}"
      shell: /bin/bash
      state: present

  - name: Add User to Sudo
    ansible.builtin.user:
      name: "{{ user }}"
      groups: sudo
      append: yes

  - name: Create .ssh Directory
    ansible.builtin.file:
      path: "/home/{{ user }}/.ssh"
      state: directory
      group: "{{ user }}"
      owner: "{{ user }}"
      mode: "0700"

  - name: Add authorized_keys
    ansible.builtin.copy:
      dest: "/home/{{ user }}/.ssh/authorized_keys"
      content: "ini isi ssh..."
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0600'
