
---
# tasks file for user
- name: Create default user
  ansible.builtin.user:
    name: "{{ default_user }}"
    shell: "{{ default_user_shell }}"
    state: present
    create_home: yes
    groups: sudo
    append: yes

- name: Set authorized key
  ansible.builtin.authorized_key:
    user: "{{ default_user }}"
    key: "{{ default_user_pubkey }}"
