---
- name: Update System
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Nginx
  apt:
    name: "{{nginx_package_name}}"
    state: present

- name: Start Nginx
  service: 
    name: nginx
    state: started
    enabled: yes

- name: Salin Index ke Root
  copy:
    src: index.html
    dest: "{{nginx_root}}"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Salin Konfigurasi Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx 

