name: Check Roles

on:
  push:
    paths:
      - "provisioning-server/roles/**"
      - "provisioning-server/site.yml"
  pull_request:
    paths:
      - "provisioning-server/roles/**"
      - "provisioning-server/site.yml"
  workflow_dispatch:

jobs:
  check-roles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python & Ansible
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          pip install ansible ansible-lint

      - name: Check roles structure
        run: |
          cd provisioning-server

          echo "🔍 Checking roles in provisioning-server/roles..."

          # Check if roles directory exists
          if [ ! -d "roles" ]; then
            echo "❌ ERROR: roles directory not found!"
            exit 1
          fi

          # Get all roles
          ROLES=$(ls -1 roles/)
          if [ -z "$ROLES" ]; then
            echo "❌ ERROR: No roles found!"
            exit 1
          fi

          echo "📋 Found roles: $ROLES"

          # Check each role
          FAILED=false
          for role in $ROLES; do
            echo "🔸 Checking role: $role"
            
            # Check tasks/main.yml exists
            if [ ! -f "roles/$role/tasks/main.yml" ]; then
              echo "❌ ERROR: roles/$role/tasks/main.yml not found!"
              FAILED=true
            else
              echo "✅ roles/$role/tasks/main.yml found"
            fi
          done

          if [ "$FAILED" = true ]; then
            echo "❌ ERROR: Role structure check failed!"
            exit 1
          fi

          echo "✅ SUCCESS: All roles have valid structure"

      - name: Run ansible-lint
        run: |
          cd provisioning-server

          echo "🔍 Running ansible-lint on roles..."

          if ansible-lint roles/; then
            echo "✅ SUCCESS: Ansible-lint passed"
          else
            echo "❌ ERROR: Ansible-lint failed"
            exit 1
          fi

      - name: Check playbook syntax
        run: |
          cd provisioning-server

          echo "🔍 Checking playbook syntax..."

          # Check if site.yml exists
          if [ ! -f "site.yml" ]; then
            echo "⚠️ WARNING: site.yml not found, skipping syntax check"
            exit 0
          fi

          # Create temporary inventory
          echo "localhost ansible_connection=local" > inventory.tmp

          if ansible-playbook --syntax-check -i inventory.tmp site.yml; then
            echo "✅ SUCCESS: Playbook syntax is valid"
          else
            echo "❌ ERROR: Playbook syntax check failed"
            exit 1
          fi

          rm inventory.tmp

      - name: Summary
        if: always()
        run: |
          echo "📊 FINAL RESULT:"
          if [ "${{ job.status }}" = "success" ]; then
            echo "🎉 SUCCESS: All checks passed!"
            echo "✅ Role structure: OK"
            echo "✅ Ansible-lint: OK" 
            echo "✅ Playbook syntax: OK"
          else
            echo "❌ FAILED: One or more checks failed!"
            echo "Check the logs above for details."
          fi
